# Generated by Django 6.0.1 on 2026-02-15 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vetmanagementsystem', '0002_rename_note_clientcommunicationnote_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='Vetmanagementsystem.visit'),
        ),
    ]
