# Generated by Django 6.0.1 on 2026-02-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Vetmanagementsystem", "0002_patient_photo_data"),
        ("Vetmanagementsystem", "0003_alter_vitalsigns_visit"),
    ]

    operations = []
